package entities;
// Generated Jan 7, 2019 10:09:45 AM by Hibernate Tools 4.3.1



/**
 * Bangcap generated by hbm2java
 */
public class Bangcap  implements java.io.Serializable {


     private String maBangCap;
     private String tenBangCap;

    public Bangcap() {
    }

    public Bangcap(String maBangCap, String tenBangCap) {
       this.maBangCap = maBangCap;
       this.tenBangCap = tenBangCap;
    }
   
    public String getMaBangCap() {
        return this.maBangCap;
    }
    
    public void setMaBangCap(String maBangCap) {
        this.maBangCap = maBangCap;
    }
    public String getTenBangCap() {
        return this.tenBangCap;
    }
    
    public void setTenBangCap(String tenBangCap) {
        this.tenBangCap = tenBangCap;
    }




}


