package entities;
// Generated Jan 8, 2019 5:35:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Chucvu generated by hbm2java
 */
public class Chucvu  implements java.io.Serializable {


     private String maChucVu;
     private String tenChucVu;
     private String maPhongBan;
     private Set nhanviens = new HashSet(0);

    public Chucvu() {
    }

	
    public Chucvu(String maChucVu, String tenChucVu, String maPhongBan) {
        this.maChucVu = maChucVu;
        this.tenChucVu = tenChucVu;
        this.maPhongBan = maPhongBan;
    }
    public Chucvu(String maChucVu, String tenChucVu, String maPhongBan, Set nhanviens) {
       this.maChucVu = maChucVu;
       this.tenChucVu = tenChucVu;
       this.maPhongBan = maPhongBan;
       this.nhanviens = nhanviens;
    }
   
    public String getMaChucVu() {
        return this.maChucVu;
    }
    
    public void setMaChucVu(String maChucVu) {
        this.maChucVu = maChucVu;
    }
    public String getTenChucVu() {
        return this.tenChucVu;
    }
    
    public void setTenChucVu(String tenChucVu) {
        this.tenChucVu = tenChucVu;
    }
    public String getMaPhongBan() {
        return this.maPhongBan;
    }
    
    public void setMaPhongBan(String maPhongBan) {
        this.maPhongBan = maPhongBan;
    }
    public Set getNhanviens() {
        return this.nhanviens;
    }
    
    public void setNhanviens(Set nhanviens) {
        this.nhanviens = nhanviens;
    }




}


