package entities;
// Generated Jan 7, 2019 10:09:45 AM by Hibernate Tools 4.3.1



/**
 * Chucvu generated by hbm2java
 */
public class Chucvu  implements java.io.Serializable {


     private String maChucVu;
     private String tenChucVu;
     private String maPhongBan;

    public Chucvu() {
    }

    public Chucvu(String maChucVu, String tenChucVu, String maPhongBan) {
       this.maChucVu = maChucVu;
       this.tenChucVu = tenChucVu;
       this.maPhongBan = maPhongBan;
    }
   
    public String getMaChucVu() {
        return this.maChucVu;
    }
    
    public void setMaChucVu(String maChucVu) {
        this.maChucVu = maChucVu;
    }
    public String getTenChucVu() {
        return this.tenChucVu;
    }
    
    public void setTenChucVu(String tenChucVu) {
        this.tenChucVu = tenChucVu;
    }
    public String getMaPhongBan() {
        return this.maPhongBan;
    }
    
    public void setMaPhongBan(String maPhongBan) {
        this.maPhongBan = maPhongBan;
    }




}


