package entities;
// Generated Jan 7, 2019 10:09:45 AM by Hibernate Tools 4.3.1



/**
 * Congviec generated by hbm2java
 */
public class Congviec  implements java.io.Serializable {


     private String maCongViec;
     private String tenCongViec;

    public Congviec() {
    }

    public Congviec(String maCongViec, String tenCongViec) {
       this.maCongViec = maCongViec;
       this.tenCongViec = tenCongViec;
    }
   
    public String getMaCongViec() {
        return this.maCongViec;
    }
    
    public void setMaCongViec(String maCongViec) {
        this.maCongViec = maCongViec;
    }
    public String getTenCongViec() {
        return this.tenCongViec;
    }
    
    public void setTenCongViec(String tenCongViec) {
        this.tenCongViec = tenCongViec;
    }




}


