package entities;
// Generated Jan 9, 2019 4:59:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Congviec generated by hbm2java
 */
public class Congviec  implements java.io.Serializable {


     private String maCongViec;
     private String tenCongViec;
     private Set nhanviens = new HashSet(0);

    public Congviec() {
    }

	
    public Congviec(String maCongViec, String tenCongViec) {
        this.maCongViec = maCongViec;
        this.tenCongViec = tenCongViec;
    }
    public Congviec(String maCongViec, String tenCongViec, Set nhanviens) {
       this.maCongViec = maCongViec;
       this.tenCongViec = tenCongViec;
       this.nhanviens = nhanviens;
    }
   
    public String getMaCongViec() {
        return this.maCongViec;
    }
    
    public void setMaCongViec(String maCongViec) {
        this.maCongViec = maCongViec;
    }
    public String getTenCongViec() {
        return this.tenCongViec;
    }
    
    public void setTenCongViec(String tenCongViec) {
        this.tenCongViec = tenCongViec;
    }
    public Set getNhanviens() {
        return this.nhanviens;
    }
    
    public void setNhanviens(Set nhanviens) {
        this.nhanviens = nhanviens;
    }




}


