package entities;
// Generated Jan 9, 2019 4:59:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Dantoc generated by hbm2java
 */
public class Dantoc  implements java.io.Serializable {


     private String maDanToc;
     private String tenDanToc;
     private Set nhanviens = new HashSet(0);

    public Dantoc() {
    }

	
    public Dantoc(String maDanToc, String tenDanToc) {
        this.maDanToc = maDanToc;
        this.tenDanToc = tenDanToc;
    }
    public Dantoc(String maDanToc, String tenDanToc, Set nhanviens) {
       this.maDanToc = maDanToc;
       this.tenDanToc = tenDanToc;
       this.nhanviens = nhanviens;
    }
   
    public String getMaDanToc() {
        return this.maDanToc;
    }
    
    public void setMaDanToc(String maDanToc) {
        this.maDanToc = maDanToc;
    }
    public String getTenDanToc() {
        return this.tenDanToc;
    }
    
    public void setTenDanToc(String tenDanToc) {
        this.tenDanToc = tenDanToc;
    }
    public Set getNhanviens() {
        return this.nhanviens;
    }
    
    public void setNhanviens(Set nhanviens) {
        this.nhanviens = nhanviens;
    }




}


