package entities;
// Generated Jan 7, 2019 10:09:45 AM by Hibernate Tools 4.3.1



/**
 * Dantoc generated by hbm2java
 */
public class Dantoc  implements java.io.Serializable {


     private String maDanToc;
     private String tenDanToc;

    public Dantoc() {
    }

    public Dantoc(String maDanToc, String tenDanToc) {
       this.maDanToc = maDanToc;
       this.tenDanToc = tenDanToc;
    }
   
    public String getMaDanToc() {
        return this.maDanToc;
    }
    
    public void setMaDanToc(String maDanToc) {
        this.maDanToc = maDanToc;
    }
    public String getTenDanToc() {
        return this.tenDanToc;
    }
    
    public void setTenDanToc(String tenDanToc) {
        this.tenDanToc = tenDanToc;
    }




}


