package entities;
// Generated Jan 7, 2019 10:09:45 AM by Hibernate Tools 4.3.1



/**
 * Hocvan generated by hbm2java
 */
public class Hocvan  implements java.io.Serializable {


     private String maHocVan;
     private String tenHocVan;

    public Hocvan() {
    }

    public Hocvan(String maHocVan, String tenHocVan) {
       this.maHocVan = maHocVan;
       this.tenHocVan = tenHocVan;
    }
   
    public String getMaHocVan() {
        return this.maHocVan;
    }
    
    public void setMaHocVan(String maHocVan) {
        this.maHocVan = maHocVan;
    }
    public String getTenHocVan() {
        return this.tenHocVan;
    }
    
    public void setTenHocVan(String tenHocVan) {
        this.tenHocVan = tenHocVan;
    }




}


