package entities;
// Generated Jan 8, 2019 5:35:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hocvan generated by hbm2java
 */
public class Hocvan  implements java.io.Serializable {


     private String maHocVan;
     private String tenHocVan;
     private Set nhanviens = new HashSet(0);

    public Hocvan() {
    }

	
    public Hocvan(String maHocVan, String tenHocVan) {
        this.maHocVan = maHocVan;
        this.tenHocVan = tenHocVan;
    }
    public Hocvan(String maHocVan, String tenHocVan, Set nhanviens) {
       this.maHocVan = maHocVan;
       this.tenHocVan = tenHocVan;
       this.nhanviens = nhanviens;
    }
   
    public String getMaHocVan() {
        return this.maHocVan;
    }
    
    public void setMaHocVan(String maHocVan) {
        this.maHocVan = maHocVan;
    }
    public String getTenHocVan() {
        return this.tenHocVan;
    }
    
    public void setTenHocVan(String tenHocVan) {
        this.tenHocVan = tenHocVan;
    }
    public Set getNhanviens() {
        return this.nhanviens;
    }
    
    public void setNhanviens(Set nhanviens) {
        this.nhanviens = nhanviens;
    }




}


