package entities;
// Generated Jan 9, 2019 4:59:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Loainhanvien generated by hbm2java
 */
public class Loainhanvien  implements java.io.Serializable {


     private String maLoaiNv;
     private String tenLoaiNv;
     private Set nhanviens = new HashSet(0);

    public Loainhanvien() {
    }

	
    public Loainhanvien(String maLoaiNv, String tenLoaiNv) {
        this.maLoaiNv = maLoaiNv;
        this.tenLoaiNv = tenLoaiNv;
    }
    public Loainhanvien(String maLoaiNv, String tenLoaiNv, Set nhanviens) {
       this.maLoaiNv = maLoaiNv;
       this.tenLoaiNv = tenLoaiNv;
       this.nhanviens = nhanviens;
    }
   
    public String getMaLoaiNv() {
        return this.maLoaiNv;
    }
    
    public void setMaLoaiNv(String maLoaiNv) {
        this.maLoaiNv = maLoaiNv;
    }
    public String getTenLoaiNv() {
        return this.tenLoaiNv;
    }
    
    public void setTenLoaiNv(String tenLoaiNv) {
        this.tenLoaiNv = tenLoaiNv;
    }
    public Set getNhanviens() {
        return this.nhanviens;
    }
    
    public void setNhanviens(Set nhanviens) {
        this.nhanviens = nhanviens;
    }




}


