package entities;
// Generated Jan 9, 2019 4:59:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Ngoaingu generated by hbm2java
 */
public class Ngoaingu  implements java.io.Serializable {


     private String maNgoaiNgu;
     private String tenNgoaiNgu;
     private Set nhanviens = new HashSet(0);

    public Ngoaingu() {
    }

	
    public Ngoaingu(String maNgoaiNgu, String tenNgoaiNgu) {
        this.maNgoaiNgu = maNgoaiNgu;
        this.tenNgoaiNgu = tenNgoaiNgu;
    }
    public Ngoaingu(String maNgoaiNgu, String tenNgoaiNgu, Set nhanviens) {
       this.maNgoaiNgu = maNgoaiNgu;
       this.tenNgoaiNgu = tenNgoaiNgu;
       this.nhanviens = nhanviens;
    }
   
    public String getMaNgoaiNgu() {
        return this.maNgoaiNgu;
    }
    
    public void setMaNgoaiNgu(String maNgoaiNgu) {
        this.maNgoaiNgu = maNgoaiNgu;
    }
    public String getTenNgoaiNgu() {
        return this.tenNgoaiNgu;
    }
    
    public void setTenNgoaiNgu(String tenNgoaiNgu) {
        this.tenNgoaiNgu = tenNgoaiNgu;
    }
    public Set getNhanviens() {
        return this.nhanviens;
    }
    
    public void setNhanviens(Set nhanviens) {
        this.nhanviens = nhanviens;
    }




}


