package entities;
// Generated Jan 7, 2019 10:09:45 AM by Hibernate Tools 4.3.1



/**
 * Ngoaingu generated by hbm2java
 */
public class Ngoaingu  implements java.io.Serializable {


     private String maNgoaiNgu;
     private String tenNgoaiNgu;

    public Ngoaingu() {
    }

    public Ngoaingu(String maNgoaiNgu, String tenNgoaiNgu) {
       this.maNgoaiNgu = maNgoaiNgu;
       this.tenNgoaiNgu = tenNgoaiNgu;
    }
   
    public String getMaNgoaiNgu() {
        return this.maNgoaiNgu;
    }
    
    public void setMaNgoaiNgu(String maNgoaiNgu) {
        this.maNgoaiNgu = maNgoaiNgu;
    }
    public String getTenNgoaiNgu() {
        return this.tenNgoaiNgu;
    }
    
    public void setTenNgoaiNgu(String tenNgoaiNgu) {
        this.tenNgoaiNgu = tenNgoaiNgu;
    }




}


