package entities;
// Generated Jan 7, 2019 10:09:45 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Nhanvien generated by hbm2java
 */
public class Nhanvien  implements java.io.Serializable {


     private String maNhanVien;
     private String hoTen;
     private String biDanh;
     private String diDong;
     private String dienThoaiNha;
     private Date ngayVaoLam;
     private String loaiNhanVien;
     private String congViec;
     private String phongBan;
     private String chucVu;
     private String email;
     private Date ngaySinh;
     private String noiSinh;
     private String tinhThanh;
     private String cmnd;
     private Date ngayCap;
     private String noiCap;
     private String queQuan;
     private String diaChi;
     private String tamTru;
     private Boolean gioiTinh;
     private Boolean honNhan;
     private double mucLuongCb;
     private float heSoLuong;
     private double mucLuong;
     private double phuCapLuong;
     private String soLaoDong;
     private Date ngayCapLd;
     private String noiCapLd;
     private String tknganHang;
     private String nganHang;
     private String hocVan;
     private String bangCap;
     private String ngoaiNgu;
     private String tinHoc;
     private String danToc;
     private String quocTich;
     private String tonGiao;

    public Nhanvien() {
    }

	
    public Nhanvien(String maNhanVien, Date ngayVaoLam, String loaiNhanVien, String congViec, String phongBan, String chucVu, double mucLuongCb, float heSoLuong, double mucLuong, double phuCapLuong, String soLaoDong, Date ngayCapLd, String noiCapLd, String tknganHang, String nganHang, String hocVan, String bangCap, String ngoaiNgu, String tinHoc, String danToc, String quocTich, String tonGiao) {
        this.maNhanVien = maNhanVien;
        this.ngayVaoLam = ngayVaoLam;
        this.loaiNhanVien = loaiNhanVien;
        this.congViec = congViec;
        this.phongBan = phongBan;
        this.chucVu = chucVu;
        this.mucLuongCb = mucLuongCb;
        this.heSoLuong = heSoLuong;
        this.mucLuong = mucLuong;
        this.phuCapLuong = phuCapLuong;
        this.soLaoDong = soLaoDong;
        this.ngayCapLd = ngayCapLd;
        this.noiCapLd = noiCapLd;
        this.tknganHang = tknganHang;
        this.nganHang = nganHang;
        this.hocVan = hocVan;
        this.bangCap = bangCap;
        this.ngoaiNgu = ngoaiNgu;
        this.tinHoc = tinHoc;
        this.danToc = danToc;
        this.quocTich = quocTich;
        this.tonGiao = tonGiao;
    }
    public Nhanvien(String maNhanVien, String hoTen, String biDanh, String diDong, String dienThoaiNha, Date ngayVaoLam, String loaiNhanVien, String congViec, String phongBan, String chucVu, String email, Date ngaySinh, String noiSinh, String tinhThanh, String cmnd, Date ngayCap, String noiCap, String queQuan, String diaChi, String tamTru, Boolean gioiTinh, Boolean honNhan, double mucLuongCb, float heSoLuong, double mucLuong, double phuCapLuong, String soLaoDong, Date ngayCapLd, String noiCapLd, String tknganHang, String nganHang, String hocVan, String bangCap, String ngoaiNgu, String tinHoc, String danToc, String quocTich, String tonGiao) {
       this.maNhanVien = maNhanVien;
       this.hoTen = hoTen;
       this.biDanh = biDanh;
       this.diDong = diDong;
       this.dienThoaiNha = dienThoaiNha;
       this.ngayVaoLam = ngayVaoLam;
       this.loaiNhanVien = loaiNhanVien;
       this.congViec = congViec;
       this.phongBan = phongBan;
       this.chucVu = chucVu;
       this.email = email;
       this.ngaySinh = ngaySinh;
       this.noiSinh = noiSinh;
       this.tinhThanh = tinhThanh;
       this.cmnd = cmnd;
       this.ngayCap = ngayCap;
       this.noiCap = noiCap;
       this.queQuan = queQuan;
       this.diaChi = diaChi;
       this.tamTru = tamTru;
       this.gioiTinh = gioiTinh;
       this.honNhan = honNhan;
       this.mucLuongCb = mucLuongCb;
       this.heSoLuong = heSoLuong;
       this.mucLuong = mucLuong;
       this.phuCapLuong = phuCapLuong;
       this.soLaoDong = soLaoDong;
       this.ngayCapLd = ngayCapLd;
       this.noiCapLd = noiCapLd;
       this.tknganHang = tknganHang;
       this.nganHang = nganHang;
       this.hocVan = hocVan;
       this.bangCap = bangCap;
       this.ngoaiNgu = ngoaiNgu;
       this.tinHoc = tinHoc;
       this.danToc = danToc;
       this.quocTich = quocTich;
       this.tonGiao = tonGiao;
    }
   
    public String getMaNhanVien() {
        return this.maNhanVien;
    }
    
    public void setMaNhanVien(String maNhanVien) {
        this.maNhanVien = maNhanVien;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getBiDanh() {
        return this.biDanh;
    }
    
    public void setBiDanh(String biDanh) {
        this.biDanh = biDanh;
    }
    public String getDiDong() {
        return this.diDong;
    }
    
    public void setDiDong(String diDong) {
        this.diDong = diDong;
    }
    public String getDienThoaiNha() {
        return this.dienThoaiNha;
    }
    
    public void setDienThoaiNha(String dienThoaiNha) {
        this.dienThoaiNha = dienThoaiNha;
    }
    public Date getNgayVaoLam() {
        return this.ngayVaoLam;
    }
    
    public void setNgayVaoLam(Date ngayVaoLam) {
        this.ngayVaoLam = ngayVaoLam;
    }
    public String getLoaiNhanVien() {
        return this.loaiNhanVien;
    }
    
    public void setLoaiNhanVien(String loaiNhanVien) {
        this.loaiNhanVien = loaiNhanVien;
    }
    public String getCongViec() {
        return this.congViec;
    }
    
    public void setCongViec(String congViec) {
        this.congViec = congViec;
    }
    public String getPhongBan() {
        return this.phongBan;
    }
    
    public void setPhongBan(String phongBan) {
        this.phongBan = phongBan;
    }
    public String getChucVu() {
        return this.chucVu;
    }
    
    public void setChucVu(String chucVu) {
        this.chucVu = chucVu;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }
    public String getNoiSinh() {
        return this.noiSinh;
    }
    
    public void setNoiSinh(String noiSinh) {
        this.noiSinh = noiSinh;
    }
    public String getTinhThanh() {
        return this.tinhThanh;
    }
    
    public void setTinhThanh(String tinhThanh) {
        this.tinhThanh = tinhThanh;
    }
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }
    public Date getNgayCap() {
        return this.ngayCap;
    }
    
    public void setNgayCap(Date ngayCap) {
        this.ngayCap = ngayCap;
    }
    public String getNoiCap() {
        return this.noiCap;
    }
    
    public void setNoiCap(String noiCap) {
        this.noiCap = noiCap;
    }
    public String getQueQuan() {
        return this.queQuan;
    }
    
    public void setQueQuan(String queQuan) {
        this.queQuan = queQuan;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getTamTru() {
        return this.tamTru;
    }
    
    public void setTamTru(String tamTru) {
        this.tamTru = tamTru;
    }
    public Boolean getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(Boolean gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public Boolean getHonNhan() {
        return this.honNhan;
    }
    
    public void setHonNhan(Boolean honNhan) {
        this.honNhan = honNhan;
    }
    public double getMucLuongCb() {
        return this.mucLuongCb;
    }
    
    public void setMucLuongCb(double mucLuongCb) {
        this.mucLuongCb = mucLuongCb;
    }
    public float getHeSoLuong() {
        return this.heSoLuong;
    }
    
    public void setHeSoLuong(float heSoLuong) {
        this.heSoLuong = heSoLuong;
    }
    public double getMucLuong() {
        return this.mucLuong;
    }
    
    public void setMucLuong(double mucLuong) {
        this.mucLuong = mucLuong;
    }
    public double getPhuCapLuong() {
        return this.phuCapLuong;
    }
    
    public void setPhuCapLuong(double phuCapLuong) {
        this.phuCapLuong = phuCapLuong;
    }
    public String getSoLaoDong() {
        return this.soLaoDong;
    }
    
    public void setSoLaoDong(String soLaoDong) {
        this.soLaoDong = soLaoDong;
    }
    public Date getNgayCapLd() {
        return this.ngayCapLd;
    }
    
    public void setNgayCapLd(Date ngayCapLd) {
        this.ngayCapLd = ngayCapLd;
    }
    public String getNoiCapLd() {
        return this.noiCapLd;
    }
    
    public void setNoiCapLd(String noiCapLd) {
        this.noiCapLd = noiCapLd;
    }
    public String getTknganHang() {
        return this.tknganHang;
    }
    
    public void setTknganHang(String tknganHang) {
        this.tknganHang = tknganHang;
    }
    public String getNganHang() {
        return this.nganHang;
    }
    
    public void setNganHang(String nganHang) {
        this.nganHang = nganHang;
    }
    public String getHocVan() {
        return this.hocVan;
    }
    
    public void setHocVan(String hocVan) {
        this.hocVan = hocVan;
    }
    public String getBangCap() {
        return this.bangCap;
    }
    
    public void setBangCap(String bangCap) {
        this.bangCap = bangCap;
    }
    public String getNgoaiNgu() {
        return this.ngoaiNgu;
    }
    
    public void setNgoaiNgu(String ngoaiNgu) {
        this.ngoaiNgu = ngoaiNgu;
    }
    public String getTinHoc() {
        return this.tinHoc;
    }
    
    public void setTinHoc(String tinHoc) {
        this.tinHoc = tinHoc;
    }
    public String getDanToc() {
        return this.danToc;
    }
    
    public void setDanToc(String danToc) {
        this.danToc = danToc;
    }
    public String getQuocTich() {
        return this.quocTich;
    }
    
    public void setQuocTich(String quocTich) {
        this.quocTich = quocTich;
    }
    public String getTonGiao() {
        return this.tonGiao;
    }
    
    public void setTonGiao(String tonGiao) {
        this.tonGiao = tonGiao;
    }




}


