package entities;
// Generated Jan 9, 2019 4:59:26 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Nhanvien generated by hbm2java
 */
public class Nhanvien  implements java.io.Serializable {


     private String maNhanVien;
     private Bangcap bangcap;
     private Chucvu chucvu;
     private Congviec congviec;
     private Dantoc dantoc;
     private Hocvan hocvan;
     private Loainhanvien loainhanvien;
     private Ngoaingu ngoaingu;
     private Phongban phongban;
     private Quoctich quoctich;
     private Tinhoc tinhoc;
     private Tinhthanh tinhthanh;
     private Tongiao tongiao;
     private String hoTen;
     private String biDanh;
     private String diDong;
     private String dienThoaiNha;
     private Date ngayVaoLam;
     private String email;
     private Date ngaySinh;
     private String noiSinh;
     private String cmnd;
     private Date ngayCap;
     private String noiCap;
     private String queQuan;
     private String diaChi;
     private String tamTru;
     private Boolean gioiTinh;
     private Boolean honNhan;
     private long mucLuongCb;
     private float heSoLuong;
     private long mucLuong;
     private long phuCapLuong;
     private String soLaoDong;
     private Date ngayCapLd;
     private String noiCapLd;
     private String tknganHang;
     private String nganHang;

    public Nhanvien() {
    }

	
    public Nhanvien(String maNhanVien, Bangcap bangcap, Chucvu chucvu, Congviec congviec, Dantoc dantoc, Hocvan hocvan, Loainhanvien loainhanvien, Ngoaingu ngoaingu, Phongban phongban, Quoctich quoctich, Tinhoc tinhoc, Tongiao tongiao, Date ngayVaoLam, long mucLuongCb, float heSoLuong, long mucLuong, long phuCapLuong, String soLaoDong, Date ngayCapLd, String noiCapLd, String tknganHang, String nganHang) {
        this.maNhanVien = maNhanVien;
        this.bangcap = bangcap;
        this.chucvu = chucvu;
        this.congviec = congviec;
        this.dantoc = dantoc;
        this.hocvan = hocvan;
        this.loainhanvien = loainhanvien;
        this.ngoaingu = ngoaingu;
        this.phongban = phongban;
        this.quoctich = quoctich;
        this.tinhoc = tinhoc;
        this.tongiao = tongiao;
        this.ngayVaoLam = ngayVaoLam;
        this.mucLuongCb = mucLuongCb;
        this.heSoLuong = heSoLuong;
        this.mucLuong = mucLuong;
        this.phuCapLuong = phuCapLuong;
        this.soLaoDong = soLaoDong;
        this.ngayCapLd = ngayCapLd;
        this.noiCapLd = noiCapLd;
        this.tknganHang = tknganHang;
        this.nganHang = nganHang;
    }
    public Nhanvien(String maNhanVien, Bangcap bangcap, Chucvu chucvu, Congviec congviec, Dantoc dantoc, Hocvan hocvan, Loainhanvien loainhanvien, Ngoaingu ngoaingu, Phongban phongban, Quoctich quoctich, Tinhoc tinhoc, Tinhthanh tinhthanh, Tongiao tongiao, String hoTen, String biDanh, String diDong, String dienThoaiNha, Date ngayVaoLam, String email, Date ngaySinh, String noiSinh, String cmnd, Date ngayCap, String noiCap, String queQuan, String diaChi, String tamTru, Boolean gioiTinh, Boolean honNhan, long mucLuongCb, float heSoLuong, long mucLuong, long phuCapLuong, String soLaoDong, Date ngayCapLd, String noiCapLd, String tknganHang, String nganHang) {
       this.maNhanVien = maNhanVien;
       this.bangcap = bangcap;
       this.chucvu = chucvu;
       this.congviec = congviec;
       this.dantoc = dantoc;
       this.hocvan = hocvan;
       this.loainhanvien = loainhanvien;
       this.ngoaingu = ngoaingu;
       this.phongban = phongban;
       this.quoctich = quoctich;
       this.tinhoc = tinhoc;
       this.tinhthanh = tinhthanh;
       this.tongiao = tongiao;
       this.hoTen = hoTen;
       this.biDanh = biDanh;
       this.diDong = diDong;
       this.dienThoaiNha = dienThoaiNha;
       this.ngayVaoLam = ngayVaoLam;
       this.email = email;
       this.ngaySinh = ngaySinh;
       this.noiSinh = noiSinh;
       this.cmnd = cmnd;
       this.ngayCap = ngayCap;
       this.noiCap = noiCap;
       this.queQuan = queQuan;
       this.diaChi = diaChi;
       this.tamTru = tamTru;
       this.gioiTinh = gioiTinh;
       this.honNhan = honNhan;
       this.mucLuongCb = mucLuongCb;
       this.heSoLuong = heSoLuong;
       this.mucLuong = mucLuong;
       this.phuCapLuong = phuCapLuong;
       this.soLaoDong = soLaoDong;
       this.ngayCapLd = ngayCapLd;
       this.noiCapLd = noiCapLd;
       this.tknganHang = tknganHang;
       this.nganHang = nganHang;
    }
   
    public String getMaNhanVien() {
        return this.maNhanVien;
    }
    
    public void setMaNhanVien(String maNhanVien) {
        this.maNhanVien = maNhanVien;
    }
    public Bangcap getBangcap() {
        return this.bangcap;
    }
    
    public void setBangcap(Bangcap bangcap) {
        this.bangcap = bangcap;
    }
    public Chucvu getChucvu() {
        return this.chucvu;
    }
    
    public void setChucvu(Chucvu chucvu) {
        this.chucvu = chucvu;
    }
    public Congviec getCongviec() {
        return this.congviec;
    }
    
    public void setCongviec(Congviec congviec) {
        this.congviec = congviec;
    }
    public Dantoc getDantoc() {
        return this.dantoc;
    }
    
    public void setDantoc(Dantoc dantoc) {
        this.dantoc = dantoc;
    }
    public Hocvan getHocvan() {
        return this.hocvan;
    }
    
    public void setHocvan(Hocvan hocvan) {
        this.hocvan = hocvan;
    }
    public Loainhanvien getLoainhanvien() {
        return this.loainhanvien;
    }
    
    public void setLoainhanvien(Loainhanvien loainhanvien) {
        this.loainhanvien = loainhanvien;
    }
    public Ngoaingu getNgoaingu() {
        return this.ngoaingu;
    }
    
    public void setNgoaingu(Ngoaingu ngoaingu) {
        this.ngoaingu = ngoaingu;
    }
    public Phongban getPhongban() {
        return this.phongban;
    }
    
    public void setPhongban(Phongban phongban) {
        this.phongban = phongban;
    }
    public Quoctich getQuoctich() {
        return this.quoctich;
    }
    
    public void setQuoctich(Quoctich quoctich) {
        this.quoctich = quoctich;
    }
    public Tinhoc getTinhoc() {
        return this.tinhoc;
    }
    
    public void setTinhoc(Tinhoc tinhoc) {
        this.tinhoc = tinhoc;
    }
    public Tinhthanh getTinhthanh() {
        return this.tinhthanh;
    }
    
    public void setTinhthanh(Tinhthanh tinhthanh) {
        this.tinhthanh = tinhthanh;
    }
    public Tongiao getTongiao() {
        return this.tongiao;
    }
    
    public void setTongiao(Tongiao tongiao) {
        this.tongiao = tongiao;
    }
    public String getHoTen() {
        return this.hoTen;
    }
    
    public void setHoTen(String hoTen) {
        this.hoTen = hoTen;
    }
    public String getBiDanh() {
        return this.biDanh;
    }
    
    public void setBiDanh(String biDanh) {
        this.biDanh = biDanh;
    }
    public String getDiDong() {
        return this.diDong;
    }
    
    public void setDiDong(String diDong) {
        this.diDong = diDong;
    }
    public String getDienThoaiNha() {
        return this.dienThoaiNha;
    }
    
    public void setDienThoaiNha(String dienThoaiNha) {
        this.dienThoaiNha = dienThoaiNha;
    }
    public Date getNgayVaoLam() {
        return this.ngayVaoLam;
    }
    
    public void setNgayVaoLam(Date ngayVaoLam) {
        this.ngayVaoLam = ngayVaoLam;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getNgaySinh() {
        return this.ngaySinh;
    }
    
    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }
    public String getNoiSinh() {
        return this.noiSinh;
    }
    
    public void setNoiSinh(String noiSinh) {
        this.noiSinh = noiSinh;
    }
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }
    public Date getNgayCap() {
        return this.ngayCap;
    }
    
    public void setNgayCap(Date ngayCap) {
        this.ngayCap = ngayCap;
    }
    public String getNoiCap() {
        return this.noiCap;
    }
    
    public void setNoiCap(String noiCap) {
        this.noiCap = noiCap;
    }
    public String getQueQuan() {
        return this.queQuan;
    }
    
    public void setQueQuan(String queQuan) {
        this.queQuan = queQuan;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getTamTru() {
        return this.tamTru;
    }
    
    public void setTamTru(String tamTru) {
        this.tamTru = tamTru;
    }
    public Boolean getGioiTinh() {
        return this.gioiTinh;
    }
    
    public void setGioiTinh(Boolean gioiTinh) {
        this.gioiTinh = gioiTinh;
    }
    public Boolean getHonNhan() {
        return this.honNhan;
    }
    
    public void setHonNhan(Boolean honNhan) {
        this.honNhan = honNhan;
    }
    public long getMucLuongCb() {
        return this.mucLuongCb;
    }
    
    public void setMucLuongCb(long mucLuongCb) {
        this.mucLuongCb = mucLuongCb;
    }
    public float getHeSoLuong() {
        return this.heSoLuong;
    }
    
    public void setHeSoLuong(float heSoLuong) {
        this.heSoLuong = heSoLuong;
    }
    public long getMucLuong() {
        return this.mucLuong;
    }
    
    public void setMucLuong(long mucLuong) {
        this.mucLuong = mucLuong;
    }
    public long getPhuCapLuong() {
        return this.phuCapLuong;
    }
    
    public void setPhuCapLuong(long phuCapLuong) {
        this.phuCapLuong = phuCapLuong;
    }
    public String getSoLaoDong() {
        return this.soLaoDong;
    }
    
    public void setSoLaoDong(String soLaoDong) {
        this.soLaoDong = soLaoDong;
    }
    public Date getNgayCapLd() {
        return this.ngayCapLd;
    }
    
    public void setNgayCapLd(Date ngayCapLd) {
        this.ngayCapLd = ngayCapLd;
    }
    public String getNoiCapLd() {
        return this.noiCapLd;
    }
    
    public void setNoiCapLd(String noiCapLd) {
        this.noiCapLd = noiCapLd;
    }
    public String getTknganHang() {
        return this.tknganHang;
    }
    
    public void setTknganHang(String tknganHang) {
        this.tknganHang = tknganHang;
    }
    public String getNganHang() {
        return this.nganHang;
    }
    
    public void setNganHang(String nganHang) {
        this.nganHang = nganHang;
    }




}


