package entities;
// Generated Jan 8, 2019 5:35:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Phongban generated by hbm2java
 */
public class Phongban  implements java.io.Serializable {


     private String maPhongBan;
     private String tenPhongBan;
     private Set nhanviens = new HashSet(0);

    public Phongban() {
    }

	
    public Phongban(String maPhongBan, String tenPhongBan) {
        this.maPhongBan = maPhongBan;
        this.tenPhongBan = tenPhongBan;
    }
    public Phongban(String maPhongBan, String tenPhongBan, Set nhanviens) {
       this.maPhongBan = maPhongBan;
       this.tenPhongBan = tenPhongBan;
       this.nhanviens = nhanviens;
    }
   
    public String getMaPhongBan() {
        return this.maPhongBan;
    }
    
    public void setMaPhongBan(String maPhongBan) {
        this.maPhongBan = maPhongBan;
    }
    public String getTenPhongBan() {
        return this.tenPhongBan;
    }
    
    public void setTenPhongBan(String tenPhongBan) {
        this.tenPhongBan = tenPhongBan;
    }
    public Set getNhanviens() {
        return this.nhanviens;
    }
    
    public void setNhanviens(Set nhanviens) {
        this.nhanviens = nhanviens;
    }




}


