package entities;
// Generated Jan 7, 2019 10:09:45 AM by Hibernate Tools 4.3.1



/**
 * Quoctich generated by hbm2java
 */
public class Quoctich  implements java.io.Serializable {


     private String maQuocTich;
     private String tenQuocTich;

    public Quoctich() {
    }

    public Quoctich(String maQuocTich, String tenQuocTich) {
       this.maQuocTich = maQuocTich;
       this.tenQuocTich = tenQuocTich;
    }
   
    public String getMaQuocTich() {
        return this.maQuocTich;
    }
    
    public void setMaQuocTich(String maQuocTich) {
        this.maQuocTich = maQuocTich;
    }
    public String getTenQuocTich() {
        return this.tenQuocTich;
    }
    
    public void setTenQuocTich(String tenQuocTich) {
        this.tenQuocTich = tenQuocTich;
    }




}


