package entities;
// Generated Jan 7, 2019 10:09:45 AM by Hibernate Tools 4.3.1



/**
 * Tinhthanh generated by hbm2java
 */
public class Tinhthanh  implements java.io.Serializable {


     private String maTinhThanh;
     private String tenTinhThanh;

    public Tinhthanh() {
    }

    public Tinhthanh(String maTinhThanh, String tenTinhThanh) {
       this.maTinhThanh = maTinhThanh;
       this.tenTinhThanh = tenTinhThanh;
    }
   
    public String getMaTinhThanh() {
        return this.maTinhThanh;
    }
    
    public void setMaTinhThanh(String maTinhThanh) {
        this.maTinhThanh = maTinhThanh;
    }
    public String getTenTinhThanh() {
        return this.tenTinhThanh;
    }
    
    public void setTenTinhThanh(String tenTinhThanh) {
        this.tenTinhThanh = tenTinhThanh;
    }




}


