package entities;
// Generated Jan 9, 2019 4:59:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tinhoc generated by hbm2java
 */
public class Tinhoc  implements java.io.Serializable {


     private String maTinHoc;
     private String tenTinHoc;
     private Set nhanviens = new HashSet(0);

    public Tinhoc() {
    }

	
    public Tinhoc(String maTinHoc, String tenTinHoc) {
        this.maTinHoc = maTinHoc;
        this.tenTinHoc = tenTinHoc;
    }
    public Tinhoc(String maTinHoc, String tenTinHoc, Set nhanviens) {
       this.maTinHoc = maTinHoc;
       this.tenTinHoc = tenTinHoc;
       this.nhanviens = nhanviens;
    }
   
    public String getMaTinHoc() {
        return this.maTinHoc;
    }
    
    public void setMaTinHoc(String maTinHoc) {
        this.maTinHoc = maTinHoc;
    }
    public String getTenTinHoc() {
        return this.tenTinHoc;
    }
    
    public void setTenTinHoc(String tenTinHoc) {
        this.tenTinHoc = tenTinHoc;
    }
    public Set getNhanviens() {
        return this.nhanviens;
    }
    
    public void setNhanviens(Set nhanviens) {
        this.nhanviens = nhanviens;
    }




}


