package entities;
// Generated Jan 8, 2019 5:35:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tinhthanh generated by hbm2java
 */
public class Tinhthanh  implements java.io.Serializable {


     private String maTinhThanh;
     private String tenTinhThanh;
     private Set nhanviens = new HashSet(0);

    public Tinhthanh() {
    }

	
    public Tinhthanh(String maTinhThanh, String tenTinhThanh) {
        this.maTinhThanh = maTinhThanh;
        this.tenTinhThanh = tenTinhThanh;
    }
    public Tinhthanh(String maTinhThanh, String tenTinhThanh, Set nhanviens) {
       this.maTinhThanh = maTinhThanh;
       this.tenTinhThanh = tenTinhThanh;
       this.nhanviens = nhanviens;
    }
   
    public String getMaTinhThanh() {
        return this.maTinhThanh;
    }
    
    public void setMaTinhThanh(String maTinhThanh) {
        this.maTinhThanh = maTinhThanh;
    }
    public String getTenTinhThanh() {
        return this.tenTinhThanh;
    }
    
    public void setTenTinhThanh(String tenTinhThanh) {
        this.tenTinhThanh = tenTinhThanh;
    }
    public Set getNhanviens() {
        return this.nhanviens;
    }
    
    public void setNhanviens(Set nhanviens) {
        this.nhanviens = nhanviens;
    }




}


