package entities;
// Generated Jan 7, 2019 10:09:45 AM by Hibernate Tools 4.3.1



/**
 * Tinhoc generated by hbm2java
 */
public class Tinhoc  implements java.io.Serializable {


     private String maTinHoc;
     private String tenTinHoc;

    public Tinhoc() {
    }

    public Tinhoc(String maTinHoc, String tenTinHoc) {
       this.maTinHoc = maTinHoc;
       this.tenTinHoc = tenTinHoc;
    }
   
    public String getMaTinHoc() {
        return this.maTinHoc;
    }
    
    public void setMaTinHoc(String maTinHoc) {
        this.maTinHoc = maTinHoc;
    }
    public String getTenTinHoc() {
        return this.tenTinHoc;
    }
    
    public void setTenTinHoc(String tenTinHoc) {
        this.tenTinHoc = tenTinHoc;
    }




}


