package entities;
// Generated Jan 7, 2019 10:09:45 AM by Hibernate Tools 4.3.1



/**
 * Tongiao generated by hbm2java
 */
public class Tongiao  implements java.io.Serializable {


     private String maTonGiao;
     private String tenTonGiao;

    public Tongiao() {
    }

    public Tongiao(String maTonGiao, String tenTonGiao) {
       this.maTonGiao = maTonGiao;
       this.tenTonGiao = tenTonGiao;
    }
   
    public String getMaTonGiao() {
        return this.maTonGiao;
    }
    
    public void setMaTonGiao(String maTonGiao) {
        this.maTonGiao = maTonGiao;
    }
    public String getTenTonGiao() {
        return this.tenTonGiao;
    }
    
    public void setTenTonGiao(String tenTonGiao) {
        this.tenTonGiao = tenTonGiao;
    }




}


